import { StyleSheet } from "react-native";
import { theme } from "../../global/styles/theme";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    alignItems: "center",
  },
  title: {
    fontFamily: theme.fonts.font7_bold,
    fontSize: 38,
    top: 35,
    color: theme.colors.color4,
    marginBottom: 100,
  },
  viewMenuModal: {
    flexDirection: "row",
  },
  bodyResidentialValue: {
    alignItems: "center",
    flexDirection: "column",
    width: 300,
    height: 85,
    backgroundColor: theme.colors.color5,
    zIndex: 0,
    shadowOpacity: 0.5,
    shadowOffset: { width: 1.5, height: 1.5 },
    top: -40,
    borderRadius: 12,
  },
  viewResidentialValue: {
    width: 200,
    height: 30,
    backgroundColor: theme.colors.color3,
    borderRadius: 10,
    marginLeft: -40,
    zIndex: 3,
    top: 13,
  },
  residentialValue: {
    fontSize: 20,
    fontFamily: theme.fonts.font4_regular,
    color: theme.colors.color1,
    textAlign: "center",
    justifyContent: "center",
    margin: 2,
  },
  viewResidentialValue1: {
    width: 40,
    height: 30,
    backgroundColor: theme.colors.color2,
    borderRadius: 10,
    marginLeft: -195,
    zIndex: 2,
    shadowOpacity: 0.3,
    shadowOffset: { width: 1.5, height: 1.5 },
    top: 10,
  },
  residentialValue1: {
    fontSize: 20,
    fontFamily: theme.fonts.font4_regular,
    color: theme.colors.color1,
    textAlign: "center",
    justifyContent: "center",
    margin: 2,
  },
  inputInitialValue: {
    width: 200,
    height: 30,
    backgroundColor: theme.colors.color6,
    borderRadius: 10,
    top: -22,
    marginLeft: 30,
    zIndex: 1,
  },
  textInputInitialValue: {
    margin: 9,
    color: theme.colors.color1,
    fontFamily: theme.fonts.font4_regular_inter,
    marginLeft: 15,
  },
  bodyValueMonth: {
    alignItems: "center",
    flexDirection: "column",
    width: 300,
    height: 85,
    backgroundColor: theme.colors.color5,
    zIndex: 0,
    shadowOpacity: 0.5,
    shadowOffset: { width: 1.5, height: 1.5 },
    top: -40,
    borderRadius: 12,
    marginTop: 15,
  },
  viewValueMonth: {
    width: 133,
    height: 30,
    backgroundColor: theme.colors.color3,
    borderRadius: 10,
    marginLeft: -107,
    zIndex: 3,
    top: 13,
  },
  initialValueMonth: {
    fontSize: 20,
    fontFamily: theme.fonts.font4_regular,
    color: theme.colors.color1,
    textAlign: "center",
    justifyContent: "center",
    margin: 2,
  },
  viewValueMonth1: {
    width: 40,
    height: 30,
    backgroundColor: theme.colors.color2,
    borderRadius: 10,
    marginLeft: -195,
    zIndex: 2,
    shadowOpacity: 0.3,
    shadowOffset: { width: 1.5, height: 1.5 },
    top: 10,
  },
  valueMonth1: {
    fontSize: 20,
    fontFamily: theme.fonts.font4_regular,
    color: theme.colors.color1,
    textAlign: "center",
    justifyContent: "center",
    margin: 2,
  },
  inputValueMonth: {
    width: 200,
    height: 30,
    backgroundColor: theme.colors.color6,
    borderRadius: 10,
    top: -22,
    marginLeft: 30,
    zIndex: 1,
  },
  textInputValueMonth: {
    margin: 9,
    color: theme.colors.color1,
    fontFamily: theme.fonts.font4_regular_inter,
    marginLeft: 15,
  },
  bodyValueTime: {
    alignItems: "center",
    flexDirection: "column",
    width: 300,
    height: 85,
    backgroundColor: theme.colors.color5,
    zIndex: 0,
    shadowOpacity: 0.5,
    shadowOffset: { width: 1.5, height: 1.5 },
    top: -25,
    borderRadius: 12,
  },
  bodyValueFees: {
    alignItems: "center",
    flexDirection: "column",
    width: 300,
    height: 85,
    backgroundColor: theme.colors.color5,
    zIndex: 0,
    shadowOpacity: 0.5,
    shadowOffset: { width: 1.5, height: 1.5 },
    top: -10,
    borderRadius: 12,
  },
  button: {
    width: 300,
    height: 50,
    backgroundColor: theme.colors.color2,
    borderRadius: 10,
    shadowOpacity: 0.2,
    shadowRadius: 3,
    justifyContent: "center",
  },
  textButton: {
    fontSize: 23,
    textAlign: "center",
    fontFamily: theme.fonts.font4_regular,
    color: theme.colors.color6,
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  image: {
    width: 52,
    height: 52,
    right: 200,
    top: -150,
    transform: [{ rotate: "90deg" }],
  },
  viewModal1: {
    width: 200,
    height: 250,
    backgroundColor: theme.colors.color6,
    borderRadius: 15,
    top: "30%",
    left: "26%",
    shadowOpacity: 0.7,
    shadowOffset: { width: 2, height: 2 },
    zIndex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  img1: {
    top: -40,
    width: 100,
    height: 100,
  },
  modalSubtitle1: {
    margin: 10,
    top: 150,
    fontFamily: theme.fonts.font5_medium,
    position: "absolute",
    textAlign: "center",
  },
  rectButtoncloseModalIcon1: {
    position: "absolute",
    top: 215,
    left: "45%",
  },
  viewModal2: {
    width: 200,
    height: 250,
    backgroundColor: theme.colors.color6,
    borderRadius: 15,
    top: "30%",
    left: "26%",
    shadowOpacity: 0.7,
    shadowOffset: { width: 2, height: 2 },
    zIndex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalSubtitle2: {
    margin: 10,
    top: 150,
    fontFamily: theme.fonts.font8_extraBold,
    position: "absolute",
    textAlign: "center",
  },
  rectButtoncloseModalIcon2: {
    position: "absolute",
    top: 215,
    left: "45%",
  },
  viewModal3: {
    width: 200,
    height: 250,
    backgroundColor: theme.colors.color6,
    borderRadius: 15,
    top: "30%",
    left: "26%",
    shadowOpacity: 0.7,
    shadowOffset: { width: 2, height: 2 },
    zIndex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalSubtitle3: {
    margin: 10,
    top: 150,
    fontFamily: theme.fonts.font8_extraBold,
    position: "absolute",
    textAlign: "center",
  },
  rectButtoncloseModalIcon3: {
    position: "absolute",
    top: 215,
    left: "45%",
  },
});
