import { StyleSheet } from "react-native";
import { theme } from "../../global/styles/theme";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    alignItems: "center",
  },
  title: {
    fontFamily: theme.fonts.font7_bold,
    fontSize: 38,
    top: 35,
    color: theme.colors.color4,
  },
  viewMenuModal: {
    flexDirection: "row",
  },
  body: {
    width: 250,
    height: 90,
    backgroundColor: theme.colors.color2,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    top: 200,
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  textInBody: {
    fontFamily: theme.fonts.font5_medium,
    fontSize: 26,
    color: theme.colors.color6,
    top: 15,
  },
  image: {
    width: 32,
    height: 32,
    marginLeft: 125,
    top: -15,
  },
  add: {
    width: 32,
    height: 32,
    backgroundColor: theme.colors.color6,
    borderRadius: 5,
    top: 175,
    left: 115,
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
  },
  addImg: {
    transform: [{ rotate: "45deg" }],
    width: 25,
    height: 25,
    top: 146,
    left: 115,
    opacity: 0.7,
  },
  viewModal: {
    alignItems: "center",
    justifyContent: "center",
    width: 280,
    height: 170,
    backgroundColor: theme.colors.color6,
    borderRadius: 25,
    left: 66.5,
    top: 265,
    shadowColor: "#1a1a1a",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  titleModal: {
    fontFamily: theme.fonts.font6_semiBold,
    fontSize: 30,
    textAlign: "center",
    marginBottom: 10,
    top: 20,
    color: theme.colors.color3,
    position: "absolute",
  },
  viewInputForm: {
    top: -17,
  },
  textInput2: {
    width: 250,
    height: 40,
    backgroundColor: theme.colors.color5,
    borderRadius: 10,
    color: theme.colors.color1,
    paddingLeft: 50,
    position: "absolute",
    left: -125,
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 1 },
  },
  modalPatternView: {
    top: 80,
    right: 240,
    position: "absolute",
  },
  buttonLeft1: {
    width: 30,
    height: 30,
    backgroundColor: theme.colors.color2,
    borderRadius: 5,
    top: 125,
    left: 100,
    shadowOpacity: 0.15,
    position: "absolute",
  },
  buttonRight1: {
    width: 30,
    height: 30,
    backgroundColor: theme.colors.color2,
    borderRadius: 5,
    top: 125,
    left: 150,
    shadowOpacity: 0.15,
    position: "absolute",
  },
  buttonLeft2: {
    width: 30,
    height: 30,
    backgroundColor: theme.colors.color2,
    borderRadius: 5,
    top: 125,
    left: 100,
    shadowOpacity: 0.15,
    position: "absolute",
  },
  buttonRight2: {
    width: 30,
    height: 30,
    backgroundColor: theme.colors.color2,
    borderRadius: 5,
    top: 125,
    left: 150,
    shadowOpacity: 0.15,
    position: "absolute",
  },
  arrowImgLeft: {
    transform: [{ rotate: "90deg" }],
    width: 20,
    height: 20,
    opacity: 0.7,
    top: 4,
    left: 3,
  },
  arrowImgRight: {
    transform: [{ rotate: "270deg" }],
    width: 20,
    height: 20,
    opacity: 0.7,
    top: 4,
    left: 5,
  },
  targetImg: {
    width: 35,
    height: 35,
    top: 70,
    left: 130,
  },
  moneyImg: {
    width: 35,
    height: 35,
    top: 140,
    left: 250,
    transform: [{ rotate: "310deg" }],
    position: "absolute",
  },
  valueField: {
    width: 40,
    height: 40,
    backgroundColor: theme.colors.color2,
    borderRadius: 10,
    right: 105,
  },
  textValueField: {
    fontFamily: theme.fonts.font4_regular,
    fontSize: 20,
    color: theme.colors.color1,
    textAlign: "center",
    top: 7,
  },
});
