import { StyleSheet } from "react-native";
import { theme } from "../../../global/styles/theme";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    alignItems: "center",
  },
  bodyOne: {
    width: 350,
    height: 80,
    backgroundColor: theme.colors.color2,
    borderRadius: 20,
    position: "absolute",
    top: 120,
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
  },
  numberOne: {
    width: 30,
    height: 30,
    backgroundColor: theme.colors.color5,
    borderRadius: 10,
    position: "absolute",
    top: -5,
    left: -5,
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
  },
  numberTextOne: {
    color: theme.colors.color1,
    fontSize: 20,
    fontFamily: theme.fonts.font4_regular_inter,
  },
  fieldValueOne: {
    width: 170,
    height: 30,
    backgroundColor: theme.colors.color5,
    borderRadius: 10,
    position: "absolute",
    left: 180,
    top: -5,
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
  },
  fieldValueTextOne: {
    color: theme.colors.color1,
    fontSize: 12,
    fontFamily: theme.fonts.font4_regular_inter,
  },
  bodyTwo: {
    width: 350,
    height: 80,
    backgroundColor: theme.colors.color2,
    borderRadius: 20,
    position: "absolute",
    top: 220,
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
  },
  numberTwo: {
    width: 30,
    height: 30,
    backgroundColor: theme.colors.color5,
    borderRadius: 10,
    position: "absolute",
    top: -5,
    left: -5,
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
  },
  numberTextTwo: {
    color: theme.colors.color1,
    fontSize: 20,
    fontFamily: theme.fonts.font4_regular_inter,
  },
  fieldValueTwo: {
    width: 170,
    height: 30,
    backgroundColor: theme.colors.color5,
    borderRadius: 10,
    position: "absolute",
    left: 180,
    top: -5,
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
  },
  fieldValueTextTwo: {
    color: theme.colors.color1,
    fontSize: 12,
    fontFamily: theme.fonts.font4_regular_inter,
  },
  bodyThree: {
    width: 350,
    height: 80,
    backgroundColor: theme.colors.color2,
    borderRadius: 20,
    position: "absolute",
    top: 320,
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
  },
  numberThree: {
    width: 30,
    height: 30,
    backgroundColor: theme.colors.color5,
    borderRadius: 10,
    position: "absolute",
    top: -5,
    left: -5,
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
  },
  numberTextThree: {
    color: theme.colors.color1,
    fontSize: 20,
    fontFamily: theme.fonts.font4_regular_inter,
  },
  fieldValueThree: {
    width: 170,
    height: 30,
    backgroundColor: theme.colors.color5,
    borderRadius: 10,
    position: "absolute",
    left: 180,
    top: -5,
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
  },
  fieldValueTextThree: {
    color: theme.colors.color1,
    fontSize: 12,
    fontFamily: theme.fonts.font4_regular_inter,
  },
  bodyGrafic: {
    width: 350,
    height: 200,
    backgroundColor: theme.colors.color5,
    borderRadius: 20,
    position: "absolute",
    top: 420,
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
  },
});
